Start django app
wafflestudio19-5/team10-server pull request #1
Opened 2021-11-23 14:07 UTC by xxnpark

장고 앱을 열었습니다! 이름은 soundcloud로 했습니다.
* 설정 파일을 분기시켜 개발 및 로컬 환경에서 돌아가는 `dev.py`와 배포 서버에서 돌아가는 `prod.py`로 구분하였습니다.
* `dev.py`와 `prod.py`의 차이는 `DEBUG`(True 아님 False), `ALLOWED_HOSTS`(배포용 파일에는 ec2 서버 IP 추가)이고 혹시 DB도 구분하여 이용할 수도 있을 것 같아 각각 설정에 추가하긴 했습니다.
* `SECRET_KEY`와 데이터베이스 유저 비밀번호는 `secrets.json`이라는 파일에서 가져오도록 했는데, `.gitignore`에 추가하여 레포에는 올라가지 않습니다. 로컬 환경에서 이용하실 떄는 슬랙으로 보내드리는 JSON 파일을 `manage.py`와 같은 위치에 넣어주시면 될 것 같습니다.

2021-11-23 16:03 UTC, bsm2002 reviewed
한번 리뷰 확인해주세요!

2021-11-23 16:03 UTC, bsm2002 commented on soundcloud/soundcloud/settings/dev.py
> +        'HOST': 'waffle-team-10-rds.cf6av8nj1vlu.ap-northeast-2.rds.amazonaws.com',
@xxnpark `dev.py` 파일이라 DB를 rds가 아닌 자기 로컬 환경의 mysql로 설정하는게 좋을 것 같아요
`'HOST': 'localhost',`

2021-11-23 16:03 UTC, bsm2002 commented on soundcloud/soundcloud/settings/common.py
> +ROOT_URLCONF = 'SoundCloud.urls'
`SoundCloud.urls`에서 `soundcloud.urls`로 바꾸어야 할 것 같습니다!

2021-11-24 04:49 UTC, bsm2002 approved these changes
`feature/start` Approving review

2021-11-24 07:39 UTC, askrid requested changes
리뷰 하나 확인해 주세요.

2021-11-24 07:39 UTC, askrid commented on soundcloud/soundcloud/settings/prod.py
> +ALLOWED_HOSTS = [
배포 단계에서는 Nginx가 돌아가므로, ALLOWED_HOSTS에는 127.0.0.1 만 포함해주시면 될 듯 합니다.

2021-11-24 07:48 UTC, askrid approved these changes
수정했습니다.

2021-11-24 09:17 UTC, merged