Feat: Add GET /user/{user_id} 함수
wafflestudio19-5/team10-server pull request #6
Opened 2021-11-26 18:17 UTC by bsm2002

`user`로 시작하는 다른 API함수들도 한 번에 처리하기 위해 `GenericViewset`을 통한 `UserViewset `생성함

`user_id `가 `me`라면 로그인 후에만 정보 제공
일반 다른 `user_id`라면 그냥 정보 제공

Response 예시
```
{
    "profile_id": "12",
    "display_name": "smas",
    "email": "abb@gmail.com",
    "created_at": "2021-11-25T05:41:06.194195Z",
    "birthday": "2012-01-01",
    "gender": "",
    "first_name": "",
    "last_name": "",
    "city": "",
    "country": "",
    "bio": ""
}
```

2021-11-26 23:07 UTC, askrid commented on soundcloud/user/serializers.py
> +    bio = serializers.CharField(required=False)
ModelSerializer인데 굳이 필드를 따로 선언할 필요가 있나요?

2021-11-26 23:10 UTC, askrid commented on soundcloud/user/serializers.py
> +    bio = serializers.CharField(required=False)
이 필드는 굳이 필요가 없지 않을까요?

2021-11-26 23:10 UTC, askrid commented on soundcloud/user/serializers.py
> +        extra_kwargs = {'password': {'write_only': True, 'required': False}, 'last_login': {'read_only': True}}
created_at도 read_only=True여야 할 듯 합니다.

2021-11-26 23:10 UTC, askrid commented on soundcloud/user/urls.py
> +router.register('user', UserViewSet, basename='user')  # /api/v1/user/
주석에서 `/api/v1/user/`가 아니라, `/user`입니다.

2021-11-26 23:16 UTC, askrid commented on soundcloud/user/views.py
> +                return Response(status=status.HTTP_404_NOT_FOUND, data='해당 유저는 존재하지 않습니다.')
User에 해당하는 객체를 못 찾으면 `User.DoesNotExist` 에러가 발생합니다. 이걸로 예외 처리를 하거나 `get_object_or_404()`를 쓰는 것이 나아보입니다.

2021-11-26 23:22 UTC, askrid requested changes

2021-11-26 23:22 UTC, askrid commented on soundcloud/user/serializers.py
> +    bio = serializers.CharField(required=False)
`ModelSerializer`인데 이 필드들은 굳이 필요가 없지 않을까요?

2021-11-26 23:22 UTC, askrid commented on soundcloud/user/urls.py
> +router.register('user', UserViewSet, basename='user')  # /api/v1/user/
주석에서 `/api/v1/user/`가 아니라 `/user`입니다.

2021-11-26 23:22 UTC, askrid commented on soundcloud/user/views.py
> +                return Response(status=status.HTTP_404_NOT_FOUND, data='해당 유저는 존재하지 않습니다.')
`get()`으로 User 객체를 찾지 못하면 `User.DoesNotExist` 에러가 발생합니다. 이에 대한 에러 처리를 하거나, 그냥 `get_object_or_404()` 쓰는 것이 간단해 보입니다.

2021-11-26 23:22 UTC, askrid commented on soundcloud/user/serializers.py
> +        extra_kwargs = {'password': {'write_only': True, 'required': False}, 'last_login': {'read_only': True}}
`created_at`에도 `{'read_only': True}`를 넣어주는 것이 좋아 보입니다.

2021-11-27 00:39 UTC, xxnpark requested changes
전체적으로 준우님이 잘 수정해주신 것 같습니다! 근데 저희 API 문서 상으로는 API 주소가 `GET /users/{user_id}`라서 URL을 맞춰주어야 할 것 같습니다.

2021-11-27 00:39 UTC, xxnpark commented on soundcloud/user/urls.py
> +router.register('user', UserViewSet, basename='user')  # /user
```python
router.register('users', UserViewSet, basename='users')
```
로 수정해야 할 것 같습니다. (basename은 큰 상관없긴하겠죠)

2021-11-27 03:02 UTC, ksiyeon27 commented on soundcloud/user/serializers.py
> +    bio = serializers.CharField(required=False)
validate 등 UserSerializer 클래스 내부 메소드에서 사용하실 필드만 남기면 될 것 같습니다.

2021-11-27 04:02 UTC, ksiyeon27 commented
https://wafflestudio-2021-rks.slack.com/archives/C02N23KKR6W/p1637962463106400
이 슬랙 참고해서 profile_id 사용하는 방식으로 변경해야 할 것 같습니다.

2021-11-27 11:47 UTC, askrid commented on soundcloud/user/serializers.py
> +    bio = serializers.CharField(required=False)
지금은 굳이 필요해 보이지 않는 듯 합니다. 나중에 `PUT /users/{user_id}` 구현 시 필요한 필드만 추가하면 될 듯 합니다.

2021-11-27 12:30 UTC, askrid commented on soundcloud/user/urls.py
> +router.register('user', UserViewSet, basename='user')  # /user
수정했습니다!

2021-11-27 12:32 UTC, askrid commented
> https://wafflestudio-2021-rks.slack.com/archives/C02N23KKR6W/p1637962463106400 이 슬랙 참고해서 profile_id 사용하는 방식으로 변경해야 할 것 같습니다.

API의 일관성을 고려하여 슬랙에 작성한 대로 query parameter를 이용하도록 구현했습니다.

2021-11-27 12:32 UTC, askrid approved these changes

2021-12-15 11:46 UTC, ksiyeon27 approved these changes

2021-12-15 11:46 UTC, xxnpark approved these changes

2021-12-15 11:47 UTC, merged